//--Должности
export const GET_POSITION_REQUEST = 'GET_POSITION_REQUEST';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_ERROR = 'GET_POSITION_ERROR';

export const POST_POSITION_REQUEST = 'POST_POSITION_REQUEST';
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS';
export const POST_POSITION_ERROR = 'POST_POSITION_ERROR';

export const PUT_POSITION_REQUEST = 'PUT_POSITION_REQUEST';
export const PUT_POSITION_SUCCESS = 'PUT_POSITION_SUCCESS';
export const PUT_POSITION_ERROR = 'PUT_POSITION_ERROR';
//--

//--Оклады
export const GET_SALARIES_REQUEST = 'GET_SALARIES_REQUEST';
export const GET_SALARIES_SUCCESS = 'GET_SALARIES_SUCCESS';
export const GET_SALARIES_ERROR = 'GET_SALARIES_ERROR';

export const POST_SALARIES_REQUEST = 'POST_SALARIES_REQUEST';
export const POST_SALARIES_SUCCESS = 'POST_SALARIES_SUCCESS';
export const POST_SALARIES_ERROR = 'POST_SALARIES_ERROR';
//--

//--Филиалы
export const GET_OFFICES_REQUEST = 'GET_OFFICES_REQUEST';
export const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';
export const GET_OFFICES_ERROR = 'GET_OFFICES_ERROR';

export const POST_OFFICES_REQUEST = 'POST_OFFICES_REQUEST';
export const POST_OFFICES_SUCCESS = 'POST_OFFICES_SUCCESS';
export const POST_OFFICES_ERROR = 'POST_OFFICES_ERROR';

export const PUT_OFFICES_REQUEST = 'PUT_OFFICES_REQUEST';
export const PUT_OFFICES_SUCCESS = 'PUT_OFFICES_SUCCESS';
export const PUT_OFFICES_ERROR = 'PUT_OFFICES_ERROR'; 
//--

//--Сотрудники
export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const GET_EMPLOYEES_ACCOUNT_REQUEST = 'GET_EMPLOYEES_ACCOUNT_REQUEST';
export const GET_EMPLOYEES_ACCOUNT_SUCCESS = 'GET_EMPLOYEES_ACCOUNT_SUCCESS';
export const GET_EMPLOYEES_ACCOUNT_ERROR = 'GET_EMPLOYEES_ACCOUNT_ERROR';

export const PUT_EMPLOYEES_REQUEST = 'PUT_EMPLOYEES_REQUEST';
export const PUT_EMPLOYEES_SUCCESS = 'PUT_EMPLOYEES_SUCCESS';
export const PUT_EMPLOYEES_ERROR = 'PUT_EMPLOYEES_ERROR';

export const POST_EMPLOYEES_REQUEST = 'POST_EMPLOYEES_REQUEST';
export const POST_EMPLOYEES_SUCCESS = 'POST_EMPLOYEES_SUCCESS';
export const POST_EMPLOYEES_ERROR = 'POST_EMPLOYEES_ERROR';
//--

//Данные сотрудника
export const EMPLOYEES_ACCOUNT_DATA_REQUEST = 'EMPLOYEES_ACCOUNT_DATA_REQUEST';
export const EMPLOYEES_ACCOUNT_DATA_SUCCESS = 'EMPLOYEES_ACCOUNT_DATA_SUCCESS';
export const EMPLOYEES_ACCOUNT_DATA_ERROR = 'EMPLOYEES_ACCOUNT_DATA_ERROR';
//--

//Для загрузки фото
export const FILE_FORM_FOTO_UPLOADED = 'FILE_FORM_FOTO_UPLOADED';
export const FILE_FORM_FOTO_CLEAR = 'FILE_FORM_FOTO_CLEAR';
//--

//Для статуса формы
export const FORM_STATUS_REQUEST = 'FORM_STATUS_REQUEST';
export const FORM_STATUS_SUCCESS = 'FORM_STATUS_SUCCESS';
export const FORM_STATUS_ERROR = 'FORM_STATUS_ERROR';
export const FORM_STATUS_CLEAR = 'FORM_STATUS_CLEAR';
//--

//Личный кабинет (PersonalArea)
    //Исторя должности
        export const GET_POSITION_HISTORY_REQUEST = 'GET_POSITION_HISTORY_REQUEST';
        export const GET_POSITION_HISTORY_SUCCESS = 'GET_POSITION_HISTORY_SUCCESS';
        export const GET_POSITION_HISTORY_ERROR = 'GET_POSITION_HISTORY_ERROR';
    //--

    //История статуса
        export const GET_STATUS_HISTORY_REQUEST = 'GET_STATUS_HISTORY_REQUEST';
        export const GET_STATUS_HISTORY_SUCCESS = 'GET_STATUS_HISTORY_SUCCESS';
        export const GET_STATUS_HISTORY_ERROR = 'GET_STATUS_HISTORY_ERROR';
    //--

    //История исполнения
        export const GET_EXECUTION_HISTORY_REQUEST = 'GET_EXECUTION_HISTORY_REQUEST';
        export const GET_EXECUTION_HISTORY_SUCCESS = 'GET_EXECUTION_HISTORY_SUCCESS';
        export const GET_EXECUTION_HISTORY_ERROR = 'GET_EXECUTION_HISTORY_ERROR';
    //--

    //История активность 
        export const GET_ACTIVE_HISTORY_REQUEST = 'GET_ACTIVE_HISTORY_REQUEST';
        export const GET_ACTIVE_HISTORY_SUCCESS = 'GET_ACTIVE_HISTORY_SUCCESS';
        export const GET_ACTIVE_HISTORY_ERROR = 'GET_ACTIVE_HISTORY_ERROR';
    //--

    //История совмешения 
        export const GET_COMBINATION_HISTORY_REQUEST = 'GET_COMBINATION_HISTORY_REQUEST';
        export const GET_COMBINATION_HISTORY_SUCCESS = 'GET_COMBINATION_HISTORY_SUCCESS';
        export const GET_COMBINATION_HISTORY_ERROR = 'GET_COMBINATION_HISTORY_ERROR';
    //--
//--