//--Должности
export const GET_JOB_POSITION_REQUEST = 'GET_JOB_POSITION_REQUEST';
export const GET_JOB_POSITION_SUCCESS = 'GET_JOB_POSITION_SUCCESS';
export const GET_JOB_POSITION_ERROR = 'GET_JOB_POSITION_ERROR';

export const POST_JOB_POSITION_REQUEST = 'POST_JOB_POSITION_REQUEST';
export const POST_JOB_POSITION_SUCCESS = 'POST_JOB_POSITION_SUCCESS';
export const POST_JOB_POSITION_ERROR = 'POST_JOB_POSITION_ERROR';

export const PUT_JOB_POSITION_REQUEST = 'PUT_JOB_POSITION_REQUEST';
export const PUT_JOB_POSITION_SUCCESS = 'PUT_JOB_POSITION_SUCCESS';
export const PUT_JOB_POSITION_ERROR = 'PUT_JOB_POSITION_ERROR';
//--

//--Оклады
export const GET_JOB_SALARIES_REQUEST = 'GET_JOB_SALARIES_REQUEST';
export const GET_JOB_SALARIES_SUCCESS = 'GET_JOB_SALARIES_SUCCESS';
export const GET_JOB_SALARIES_ERROR = 'GET_JOB_SALARIES_ERROR';

export const POST_JOB_SALARIES_REQUEST = 'POST_JOB_SALARIES_REQUEST';
export const POST_JOB_SALARIES_SUCCESS = 'POST_JOB_SALARIES_SUCCESS';
export const POST_JOB_SALARIES_ERROR = 'POST_JOB_SALARIES_ERROR';
//--

//--Филиалы
export const GET_OFFICES_REQUEST = 'GET_OFFICES_REQUEST';
export const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';
export const GET_OFFICES_ERROR = 'GET_OFFICES_ERROR';

export const POST_OFFICES_REQUEST = 'POST_OFFICES_REQUEST';
export const POST_OFFICES_SUCCESS = 'POST_OFFICES_SUCCESS';
export const POST_OFFICES_ERROR = 'POST_OFFICES_ERROR';

export const PUT_OFFICES_REQUEST = 'PUT_OFFICES_REQUEST';
export const PUT_OFFICES_SUCCESS = 'PUT_OFFICES_SUCCESS';
export const PUT_OFFICES_ERROR = 'PUT_OFFICES_ERROR'; 
//--

//--Сотрудники
export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const POST_EMPLOYEES_REQUEST = 'POST_EMPLOYEES_REQUEST';
export const POST_EMPLOYEES_SUCCESS = 'POST_EMPLOYEES_SUCCESS';
export const POST_EMPLOYEES_ERROR = 'POST_EMPLOYEES_ERROR';
//--

export const EMPLOYEES_ACCOUNT_DATA_REQUEST = 'EMPLOYEES_ACCOUNT_DATA_REQUEST';
export const EMPLOYEES_ACCOUNT_DATA_SUCCESS = 'EMPLOYEES_ACCOUNT_DATA_SUCCESS';
export const EMPLOYEES_ACCOUNT_DATA_ERROR = 'EMPLOYEES_ACCOUNT_DATA_ERROR';

export const FILE_FORM_FOTO_UPLOADED = 'FILE_FORM_FOTO_UPLOADED';
export const FILE_FORM_FOTO_CLEAR = 'FILE_FORM_FOTO_CLEAR';